# -*- coding: utf-8 -*-
"""Assignment_1_Registration_and_Login.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BtngadMzryIoi80-E6eaEsbIH-3H3hu5
"""

def register():
    db = open("database.txt", "r")
    Username = input("Enter a username:")
    Password = input("Create password:")
    Password2 = input("Confirm Password:")
    u = []
    p = []
    for i in db:
        a,b = i.split(",")
        b = b.strip()
        u.append(a)
        p.append(b)
    data = dict(zip(u,p))
    print(data)

    if Password != Password2 :
      print("Password doesn't Match")
      register()
    else:
      if len(Password) <= 5 :
        print("Password is too Short")
        register()
      elif len(Password) >= 16 :
        print("Password is too Long")
        register()
      elif Username in u:
        print("username exist")
        register()
      else :
        db = open('database.txt', 'a')
        db.write(Username+','+Password+'\n')
        print('Success !')

#register()

def login():
    db = open("database.txt", "r")
    Username = input("Enter a username:")
    Password = input("Enter a password:")
    if not len(Username or Password) < 1 :

        u = []
        p = []
        for i in db:
            a,b = i.split(",")
            b = b.strip()
            u.append(a)
            p.append(b)
        data = dict(zip(u,p))
        
        try :
          if data[Username]:
            try :
              if Password == data[Username]:
                print('Login Success !')
                print('Hi',Username)
              else:
                print('Password or Username is Incorrect')
            except:
              print('Incorrect Password or Username')
          else:
            print("Username doen't exist")
        except:
          print('Login Error !')

def home(option=None):
	print("Welcome, please select an option")
	option = input("Login | Signup:")
	if option == "Login":
		login()
	elif option == "Signup":
		register()
	else:
		print("Please enter a valid parameter, this is case-sensitive")
home()